# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultshift',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='default_shifts', to='shift.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shift.Group'),
            preserve_default=False,
        ),
    ]
