# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_auto_20161020_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='shift_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
