# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_auto_20161025_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'permissions': (('view_shift', 'View shift'),)},
        ),
    ]
