# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
