# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_auto_20160920_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
