# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_band_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='concerts',
            field=models.IntegerField(default=0),
        ),
    ]
