# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_band_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='band',
            name='genres',
        ),
        migrations.AddField(
            model_name='band',
            name='genres',
            field=models.ManyToManyField(to='band.Genre'),
        ),
    ]
