# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_auto_20161004_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genres',
            field=models.ManyToManyField(to='band.Genre'),
        ),
    ]
