# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_band_sold_albums'),
        ('band', '0008_auto_20161004_1715'),
    ]

    operations = [
    ]
