# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0009_merge_20161006_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='concerts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='contact_phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='sold_albums',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
