# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0010_auto_20161006_0925'),
        ('band', '0010_auto_20161006_1028'),
    ]

    operations = [
    ]
