# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0011_merge_20161006_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='contact_phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
