# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0012_auto_20161006_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='bands',
            field=models.ManyToManyField(related_name='genres', to='band.Band'),
        ),
    ]
