# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0014_band_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'permissions': (('view_managing_bands', 'View managing bands'),)},
        ),
    ]
