# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20160920_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': (('accept_booking', 'Accept or reject booking'),)},
        ),
    ]
