# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20160921_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='booking.Booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[(' ', '-'), ('r', 'Rejected'), ('a', 'Accepted'), ('c', 'Cancelled'), ('m', 'Replaced')], default=' ', max_length=1),
        ),
    ]
