# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20160921_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_member', models.IntegerField()),
                ('attended', models.IntegerField()),
                ('additional_information', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='booking.Booking')),
            ],
        ),
    ]
