# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20160922_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='attended',
            new_name='attended_non_member',
        ),
    ]
