# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20160927_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='attended_member',
            new_name='ticket_sold_member',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='attended_non_member',
            new_name='ticket_sold_non_member',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_tickets_for_sale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='ticket_price_non_member',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='price_member',
            new_name='ticket_price_member',
        ),
    ]
