# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20160927_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_price_member',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ticket price member'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_price_non_member',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ticket price non-member'),
        ),
    ]
