# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20160927_1256'),
        ('booking', '0010_auto_20160927_1138'),
    ]

    operations = [
    ]
