# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_merge_20160927_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='band.Band'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venue.Venue'),
        ),
    ]
