# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20160929_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='offer_sent',
            field=models.BooleanField(default=False),
        ),
    ]
