# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_booking_offer_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[(' ', '-'), ('r', 'Rejected'), ('a', 'Accepted'), ('c', 'Cancelled'), ('m', 'Replaced'), ('e', 'Offer sent'), ('b', 'Offer accepted'), ('d', 'Offer rejected')], default=' ', max_length=1),
        ),
    ]
