# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20161006_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='offer_sent',
        ),
        migrations.AddField(
            model_name='booking',
            name='replaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[(' ', '-'), ('r', 'Rejected'), ('a', 'Accepted'), ('c', 'Cancelled'), ('e', 'Offer sent'), ('b', 'Offer accepted'), ('d', 'Offer rejected')], default=' ', max_length=1),
        ),
    ]
