# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20161009_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(0, 'Create'), (1, 'Transition')])),
                ('pre_transition_state', models.CharField(blank=True, choices=[(' ', '-'), ('r', 'Rejected'), ('a', 'Accepted'), ('c', 'Cancelled'), ('e', 'Offer sent'), ('b', 'Offer accepted'), ('d', 'Offer rejected')], max_length=1, null=True)),
                ('transition', models.CharField(blank=True, choices=[('a', 'Accept'), ('r', 'Reject'), ('o', 'Send offer'), ('o', 'Replace'), ('o', 'Cancel')], max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='replaced',
        ),
        migrations.AddField(
            model_name='bookingevent',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='booking.Booking'),
        ),
    ]
