# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20161009_2003_squashed_0021_bookingevent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical_Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guitar', models.IntegerField(blank=True)),
                ('drummset', models.IntegerField(blank=True)),
                ('keyboard', models.IntegerField(blank=True)),
                ('microphone', models.IntegerField(blank=True)),
                ('bass', models.IntegerField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_req', to='booking.Booking')),
            ],
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
