# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20161020_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technical_requirements',
            name='bass',
        ),
        migrations.RemoveField(
            model_name='technical_requirements',
            name='drummset',
        ),
        migrations.RemoveField(
            model_name='technical_requirements',
            name='guitar',
        ),
        migrations.RemoveField(
            model_name='technical_requirements',
            name='keyboard',
        ),
        migrations.RemoveField(
            model_name='technical_requirements',
            name='microphone',
        ),
        migrations.AddField(
            model_name='technical_requirements',
            name='requirements',
            field=models.TextField(default='testtest'),
            preserve_default=False,
        ),
    ]
