# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20161009_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingevent',
            name='transition',
            field=models.CharField(blank=True, choices=[('a', 'Accept'), ('r', 'Reject'), ('o', 'Send offer'), ('m', 'Replace'), ('c', 'Cancel')], max_length=1, null=True),
        ),
    ]
