# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20161020_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technical_requirements',
            name='requirements',
        ),
        migrations.AddField(
            model_name='technical_requirements',
            name='item',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technical_requirements',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technical_requirements',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_req', to='booking.Booking'),
        ),
    ]
