# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20161025_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technical_Requirements',
            new_name='TechnicalRequirements',
        ),
    ]
