# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20161025_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnicalRequirements',
            new_name='TechnicalRequirement',
        ),
    ]
