# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_bookingevent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingevent',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='booking.Booking'),
        ),
    ]
