# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20161025_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalrequirement',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
