# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20161101_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': (('accept_booking', 'Accept or reject booking'), ('transition_booking', 'Transition the booking state'), ('view_booking', 'View booking'))},
        ),
    ]
