# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('crowd_capacity', models.IntegerField()),
                ('stage_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stage_depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stage_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
