# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
