# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_venue_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'permissions': (('view_venue', 'View venue'),)},
        ),
    ]
